name: Main Workflow
on:
  push:
    branches: [master, main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.jsx"
      - "package.json"
      - "yarn.lock"
      - ".env.example"
      - "cypress/**"
      - ".github/workflows/**"
  pull_request:
    branches: [master, main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "**/*.jsx"
      - "package.json"
      - "yarn.lock"
      - ".env.example"
      - "cypress/**"
      - ".github/workflows/**"

jobs:
  nextjs:
    uses: ./.github/workflows/nextjs.yml
    secrets: inherit

  cypress:
    needs: nextjs
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
